paths:
  raw_csv:        data/raw/fake_job_postings.csv
  processed_dir:  data/processed
  tfidf_path:     data/processed/tfidf_vectorizer.joblib
  train_split:    data/processed/train.pkl
  val_split:      data/processed/val.pkl
  production_dir: models/production

models:
  mlp:
    hidden_units: [64, 32]
    dropout: 0.5
  lstm:
    vocab_size: 10000
    embed_dim: 128
    lstm_units: 64

training:
  model_type: mlp
  train_ratio: 0.8
  batch_size: 32
  epochs: 5
  decision_threshold: 0.5
  min_recall: 0.85