name: CD

on:
    push:
        branches:
          - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              push: True
              tags: ${{ secrets.DOCKERHUB_USER }}/fake-job-detection:latest
              build-args: |
                REQUIREMENTS=requirements-base.txt

          - name: Deploy (optional)
            run: |
              # e.g. kubectl set image deployment/api api=${{ secrets.DOCKERHUB_USER }}/fake-job-detection:latest
              echo "Add your deployment commands here"
